# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bbdown = {
    pname = "bbdown";
    version = "1.6.3";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-IXSK4XrdDbSbjvx0XsjZqi53mo4tTeFL3p0gegaNCA0=";
    };
  };
  clair-obscur-fix = {
    pname = "clair-obscur-fix";
    version = "0.0.15";
    src = fetchTarball {
      url = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/0.0.15/ClairObscurFix_0.0.15.zip";
      sha256 = "sha256-lJV+ujiSx/IkjLG5UcA54+3ucNscV2KBwOYnIlUMM2s=";
    };
  };
  coredump-notify = {
    pname = "coredump-notify";
    version = "7932978149036a952220e9263fab1734aea983c2";
    src = fetchgit {
      url = "https://github.com/js0ny/coredump-notify.git";
      rev = "7932978149036a952220e9263fab1734aea983c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OX4O2Oezm7a7o8bbNk7wASVSUVI2w1xJZki625RRuPo=";
    };
    date = "2026-08-15";
  };
  danmakufactory = {
    pname = "danmakufactory";
    version = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
      fetchSubmodules = false;
      sha256 = "sha256-wRQjWlG3R4IbcMedL7v36VZE3CcUkbeYwgr1Ex+7NGI=";
    };
    date = "2026-07-27";
  };
  dirstat-rs = {
    pname = "dirstat-rs";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "scullionw";
      repo = "dirstat-rs";
      rev = "v0.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-gDIUYhc+GWbQsn5DihnBJdOJ45zdwm24J2ZD2jEwGyE=";
    };
  };
  dump-tabs = {
    pname = "dump-tabs";
    version = "745e347bcf9a2bec87370a33d4929d07af09f011";
    src = fetchgit {
      url = "https://github.com/js0ny/dump-tabs.yazi.git";
      rev = "745e347bcf9a2bec87370a33d4929d07af09f011";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Etx5LX9TuiGoxLe6eIH6pYM1wXzsqQ/uY6clq/AiusY=";
    };
    date = "2026-07-09";
  };
  dwproton = {
    pname = "dwproton";
    version = "dwproton-11.0-14";
    src = fetchTarball {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-14/dwproton-11.0-14-x86_64.tar.xz";
      sha256 = "sha256-dXtOdfqIU0wWQ0OXDRbHuFTifGJ7ti+Ij4g+a/RV71Q=";
    };
  };
  emacs-kitty-graphics = {
    pname = "emacs-kitty-graphics";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "cashmeredev";
      repo = "kitty-graphics.el";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-wctqnbM7vdQndXl6uArLdfMHYdU6tdN7MWp2Rxdz668=";
    };
  };
  emacs-typst-overlay = {
    pname = "emacs-typst-overlay";
    version = "5a6428c20ce38fcfa4918ed72a45c337655a422b";
    src = fetchgit {
      url = "https://github.com/hesampakdaman/typst-overlay.git";
      rev = "5a6428c20ce38fcfa4918ed72a45c337655a422b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ihOQm460VccKBMjhp0RxaDnFivqtlXL4WLDqAqWly2M=";
    };
    date = "2026-10-03";
  };
  fast-note-sync-service = {
    pname = "fast-note-sync-service";
    version = "3.6.1";
    src = fetchFromGitHub {
      owner = "haierkeys";
      repo = "fast-note-sync-service";
      rev = "3.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-/aL25g7ePLc/RaErKiRWUc1y3MfPgLEhjqjXCgFq7zY=";
    };
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "565b0008134423e1059258b628acbf7119f5ea33";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks.git";
      rev = "565b0008134423e1059258b628acbf7119f5ea33";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qujQcAfZFbfkOe/vIOUuDuLEkImWCgV5z5raSqydGEg=";
    };
    date = "2026-10-01";
  };
  flyline = {
    pname = "flyline";
    version = "v1.9.0";
    src = fetchFromGitHub {
      owner = "HalFrgrd";
      repo = "flyline";
      rev = "v1.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-bKFTAAN+A3Po0PnVv1XYQyLWqBQT3btYUUuFu7jcCXA=";
    };
  };
  forgejo-file-icons = {
    pname = "forgejo-file-icons";
    version = "a3c399c75f1443f9431ef7051dc0ec026188bc5c";
    src = fetchgit {
      url = "https://github.com/js0ny/forgejo-file-icons.git";
      rev = "a3c399c75f1443f9431ef7051dc0ec026188bc5c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cx4lojxuk786tn8n7t0rPPYT2r/UR7qlYqqIkevMU5Q=";
    };
    date = "2026-08-28";
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.1.3";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-Mrf+Tr5nlhNcDwnqRFyYVfGSKp7+QvZNs0fBoheg8sg=";
    };
  };
  komari = {
    pname = "komari";
    version = "1.5.1";
    src = fetchTarball {
      url = "https://github.com/komari-monitor/komari/archive/refs/tags/1.5.1.tar.gz";
      sha256 = "sha256-jzZ2IroS6eJTgfGHWSywh588lHaQc5ycn0cWM8Cd5eU=";
    };
  };
  komari-agent = {
    pname = "komari-agent";
    version = "1.5.11";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari-agent";
      rev = "1.5.11";
      fetchSubmodules = false;
      sha256 = "sha256-1jemWrMcdJ4RIhcRyxmFahLQZ34Q1QSQLgO6BoHhOGw=";
    };
  };
  komari-web = {
    pname = "komari-web";
    version = "1.5.1";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari-web";
      rev = "1.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-ZJn+Grwfg2p813QQ87w39xk4lEbQsT/SbCal8lIcd3o=";
    };
  };
  limes = {
    pname = "limes";
    version = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
    src = fetchgit {
      url = "https://github.com/js0ny/limes.git";
      rev = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nt/y2H5+T9mA0Lvv23dig4BZUUGib16tPiCb0+Fg14Q=";
    };
    date = "2026-07-07";
  };
  mdformat-obsidian = {
    pname = "mdformat-obsidian";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "KyleKing";
      repo = "mdformat-obsidian";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-itt2Ukxd4eU5OCHdym6Uf8YyBzEhyEWnNTszqWYmnFw=";
    };
  };
  mpv-bilibili-sponsorblock = {
    pname = "mpv-bilibili-sponsorblock";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "test482";
      repo = "mpv-bilibili-sponsorblock";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-W3H/mHmXIdmfH8k2wFXfalF4W7WDQIDAW0wo11n3V04=";
    };
  };
  msd_lite = {
    pname = "msd_lite";
    version = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
    src = fetchFromGitHub {
      owner = "rozhuk-im";
      repo = "msd_lite";
      rev = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
      fetchSubmodules = true;
      sha256 = "sha256-+LMcsU/kfaRD/0OTN4IN84GeFOsuiGCKjtvVP4dyY6g=";
    };
    date = "2026-07-20";
  };
  navidrome-lyrics-bin = {
    pname = "navidrome-lyrics-bin";
    version = "8.1.0";
    src = fetchurl {
      url = "https://github.com/J0R6IT0/navidrome-lyrics-plugin/releases/download/v8.1.0/nd-lyrics.ndp";
      sha256 = "sha256-Kd1XG6DUu3VuYsDVxZSi1+fJzOwpUPOwJ71kxzxgVxU=";
    };
  };
  noname = {
    pname = "noname";
    version = "v1.11.6";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.6";
      fetchSubmodules = false;
      sha256 = "sha256-Zv+PUyVGfecsa2PdEkPzmSIR1dFHYIQeu+Mha5sSqrI=";
    };
  };
  oroot = {
    pname = "oroot";
    version = "99992d13696833ebb31372a2eb5072c3c1b79a33";
    src = fetchgit {
      url = "https://github.com/js0ny/oroot.git";
      rev = "99992d13696833ebb31372a2eb5072c3c1b79a33";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IEfxtTh271WtPKVZhKiz+mEFKS2ACM7aS4Bnk8n2kcc=";
    };
    date = "2026-08-02";
  };
  proton-drive-cli-darwin-arm64 = {
    pname = "proton-drive-cli-darwin-arm64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/darwin-arm64/proton-drive";
      sha256 = "sha256-3I/BTenvB/zvKP4gQFG7ZynEnPV5FwyM4a1mmiZ2lxE=";
    };
  };
  proton-drive-cli-linux-arm64 = {
    pname = "proton-drive-cli-linux-arm64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/linux-arm64/proton-drive";
      sha256 = "sha256-CGvEdApzy460kA1Rg2v/DDMt2jkLPweA2fgF/VwqX+M=";
    };
  };
  proton-drive-cli-linux-x64 = {
    pname = "proton-drive-cli-linux-x64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/linux-x64/proton-drive";
      sha256 = "sha256-lEPXcXGciSeQ2xfm8C7Nma18U1kzKfOmfHdnfc5XdzU=";
    };
  };
  ratune = {
    pname = "ratune";
    version = "v0.16.0";
    src = fetchFromGitHub {
      owner = "acmagn";
      repo = "ratune";
      rev = "v0.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-HxhK2tLLr2T7T2ThYKg16l9MWsV3bauTzjSl0NrsJGk=";
    };
  };
  rime-cantonese = {
    pname = "rime-cantonese";
    version = "259f0e48bba840c3a2e0d117539e96937f3d89bc";
    src = fetchgit {
      url = "https://github.com/rime/rime-cantonese.git";
      rev = "259f0e48bba840c3a2e0d117539e96937f3d89bc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ctyYZQVCd9Sc7oqPmP4lO1Q0TYDQILqt/BRloaEWjPg=";
    };
    date = "2026-08-13";
  };
  rime-dieghv = {
    pname = "rime-dieghv";
    version = "1709bb786a144de7be2229755011fde9034457de";
    src = fetchgit {
      url = "https://github.com/kahaani/dieghv.git";
      rev = "1709bb786a144de7be2229755011fde9034457de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMViEO0nxNEjVZbHwB0e9vSpe5TfHV7CuJoouS84Pjg=";
    };
    date = "2019-02-11";
  };
  rime-hokkien = {
    pname = "rime-hokkien";
    version = "e52e8bf337f161097cd3798c0173ba4e39b44396";
    src = fetchgit {
      url = "https://github.com/hokkien-writing/rime-hokkien.git";
      rev = "e52e8bf337f161097cd3798c0173ba4e39b44396";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-60NlGg2vLkOmth/O3o4G/n/XzJ9cB/tfPtCYRGbOnCs=";
    };
    date = "2026-05-04";
  };
  rime-latex = {
    pname = "rime-latex";
    version = "858f2abc645f0e459e468e98122470ce20b16b30";
    src = fetchgit {
      url = "https://github.com/shenlebantongying/rime_latex.git";
      rev = "858f2abc645f0e459e468e98122470ce20b16b30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i8Rgze+tQhbE+nl+JSj09ILXeUvf6MOS9Eqsuqis1n0=";
    };
    date = "2025-04-03";
  };
  rime-lmdg-zh-hans = {
    pname = "rime-lmdg-zh-hans";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-4/lY0lV6LAJ1Q+h0yALczpAiubb+FnPZfAvR7zBZImQ=";
    };
  };
  rime-lmdg-zh-hant = {
    pname = "rime-lmdg-zh-hant";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hant.gram";
      sha256 = "sha256-U7Z4zhfx2Ax13VGXa2l6XR/CzWoTZwZSBpsie0AVfJg=";
    };
  };
  rime-teochew = {
    pname = "rime-teochew";
    version = "7c80a292fee4001e28ca4f539c23924ab3fc3924";
    src = fetchgit {
      url = "https://github.com/OpenTeochew/rime-teochew.git";
      rev = "7c80a292fee4001e28ca4f539c23924ab3fc3924";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TfCY0Y1CPVJP0mV0cnAPh3y3g39z2yYQvycT97jWBuE=";
    };
    date = "2026-07-05";
  };
  rime-wanxiang-flypy = {
    pname = "rime-wanxiang-flypy";
    version = "v18.1.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v18.1.0/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-4dE4Lnuj5QwARBoy+zRiswsc/UD+ILm76PprzJDbKt0=";
    };
  };
  rime-wanxiang-zrm = {
    pname = "rime-wanxiang-zrm";
    version = "v18.1.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v18.1.0/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-HxG0FSTBHyHmgleeKfOdxdcv2xYKdQ9ovCgER3mWQOo=";
    };
  };
  sing-box-dashboard = {
    pname = "sing-box-dashboard";
    version = "edca5a83ccd91f474d7942b990b360e12292b4a8";
    src = fetchgit {
      url = "https://github.com/SagerNet/sing-box-dashboard.git";
      rev = "edca5a83ccd91f474d7942b990b360e12292b4a8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sSq6Ai4JR4fxIrLTsQJz5jg/S8XbgQtvcOM5xlxEmfA=";
    };
    date = "2026-10-02";
  };
  sioyek-python-extensions = {
    pname = "sioyek-python-extensions";
    version = "23d0407aefabc39714225f20bfdd8bbb6845a1ec";
    src = fetchgit {
      url = "https://github.com/ahrm/sioyek-python-extensions.git";
      rev = "23d0407aefabc39714225f20bfdd8bbb6845a1ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-H4LQ1YmHYuAmWwO0vPn2EVIK4BuEculUHm8W8CPkgqE=";
    };
    date = "2025-10-13";
  };
  sni-fetch = {
    pname = "sni-fetch";
    version = "v1.2";
    src = fetchFromGitHub {
      owner = "HelloLingC";
      repo = "SNI-Fetch";
      rev = "v1.2";
      fetchSubmodules = false;
      sha256 = "sha256-kdYPFMXR53qEThh1HllvyQRTEmXvLEPYRVUMPaS7yCg=";
    };
  };
  sops-nvim = {
    pname = "sops-nvim";
    version = "26592d8fab2a4c133d2a5d95e90d2ba54eb3c018";
    src = fetchgit {
      url = "https://github.com/trixnz/sops.nvim.git";
      rev = "26592d8fab2a4c133d2a5d95e90d2ba54eb3c018";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SXlI2M2BjNKEbReqTnNXITmryAboPjQJmq1IcgAMc5A=";
    };
    date = "2026-09-12";
  };
  typst-infect-nvim = {
    pname = "typst-infect-nvim";
    version = "baeaaf867e95867cd45bf9486c5ddf3b3b48b12d";
    src = fetchgit {
      url = "https://github.com/js0ny/typst-infect.nvim.git";
      rev = "baeaaf867e95867cd45bf9486c5ddf3b3b48b12d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oGQTT2ATIymmTLg6AILoZc6hMmTfjv2ChGS/+2VoanI=";
    };
    date = "2026-08-17";
  };
  udpxy = {
    pname = "udpxy";
    version = "1.0-25.2";
    src = fetchFromGitHub {
      owner = "pcherenkov";
      repo = "udpxy";
      rev = "1.0-25.2";
      fetchSubmodules = false;
      sha256 = "sha256-v+w4Y6MyJqUrgwuYUYTZW0Zn1jhW4vEpgBEQyEjvkzg=";
    };
  };
  vireo = {
    pname = "vireo";
    version = "v1.42.0";
    src = fetchFromGitHub {
      owner = "hyprlab";
      repo = "vireo";
      rev = "v1.42.0";
      fetchSubmodules = false;
      sha256 = "sha256-WRS/e/enQZPZ5HcW0mDaHHuNWHt+MuHudaBBd6rT9UU=";
    };
  };
  waywallen = {
    pname = "waywallen";
    version = "v0.4.3";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen";
      rev = "v0.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-nGTfRAUu9aPUPz/UfnMf8QJnO689/Xstl17yvWiKk1U=";
    };
  };
  waywallen-display = {
    pname = "waywallen-display";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen-display";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-qFCKUQSfx+bjbbfkj/REIf4w4U09sPCcilHI0lE6YqQ=";
    };
  };
  waywallen-main-page-webp = {
    pname = "waywallen-main-page-webp";
    version = "v0.4.3";
    src = fetchurl {
      url = "https://media.githubusercontent.com/media/waywallen/waywallen/v0.4.3/ui/assets/main_page.webp";
      sha256 = "sha256-4+RMgz8Jz3PZFWKYtSdGUBKNjq53zh/Yce+702band0=";
    };
  };
  wdotool = {
    pname = "wdotool";
    version = "v0.5.3";
    src = fetchFromGitHub {
      owner = "cushycush";
      repo = "wdotool";
      rev = "v0.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-kmEMkkU5cy2AqEzbpm4Dp+FzguzldzWqD5KSr7uskLE=";
    };
  };
  xdd = {
    pname = "xdd";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "js0ny";
      repo = "xdd";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-n58873gGhJ8p9GxEkeT7yRRc86CkiD9xBSlRluiKf54=";
    };
  };
}
