# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bbdown = {
    pname = "bbdown";
    version = "1.6.3";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-IXSK4XrdDbSbjvx0XsjZqi53mo4tTeFL3p0gegaNCA0=";
    };
  };
  clair-obscur-fix = {
    pname = "clair-obscur-fix";
    version = "0.0.15";
    src = fetchTarball {
      url = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/0.0.15/ClairObscurFix_0.0.15.zip";
      sha256 = "sha256-lJV+ujiSx/IkjLG5UcA54+3ucNscV2KBwOYnIlUMM2s=";
    };
  };
  danmakufactory = {
    pname = "danmakufactory";
    version = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
      fetchSubmodules = false;
      sha256 = "sha256-wRQjWlG3R4IbcMedL7v36VZE3CcUkbeYwgr1Ex+7NGI=";
    };
    date = "2026-07-27";
  };
  dirstat-rs = {
    pname = "dirstat-rs";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "scullionw";
      repo = "dirstat-rs";
      rev = "v0.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-gDIUYhc+GWbQsn5DihnBJdOJ45zdwm24J2ZD2jEwGyE=";
    };
  };
  dump-tabs = {
    pname = "dump-tabs";
    version = "745e347bcf9a2bec87370a33d4929d07af09f011";
    src = fetchgit {
      url = "https://github.com/js0ny/dump-tabs.yazi.git";
      rev = "745e347bcf9a2bec87370a33d4929d07af09f011";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Etx5LX9TuiGoxLe6eIH6pYM1wXzsqQ/uY6clq/AiusY=";
    };
    date = "2026-07-09";
  };
  dwproton = {
    pname = "dwproton";
    version = "dwproton-11.0-11";
    src = fetchTarball {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-11/dwproton-11.0-11-x86_64.tar.xz";
      sha256 = "sha256-p1x1UAuXLG0MpYcyrssudKwpCRlKAPPxrv7UFyPe2lI=";
    };
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "8d4814857f39c522e1e1d0bd704a168336ca1d3a";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks.git";
      rev = "8d4814857f39c522e1e1d0bd704a168336ca1d3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2R4DoAljYsJUb1f9RE0Fh0pn1/h/ugK8jhNIPeWmdsg=";
    };
    date = "2026-08-03";
  };
  flyline = {
    pname = "flyline";
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "HalFrgrd";
      repo = "flyline";
      rev = "v1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-2apK1e/Hqb8bUj9Ng7cB+pz27Hv14MXMy2JYYI7nxKE=";
    };
  };
  forgejo-file-icons = {
    pname = "forgejo-file-icons";
    version = "8d548bb720feaf31dd026457bff821cb9a030080";
    src = fetchgit {
      url = "https://github.com/js0ny/forgejo-file-icons.git";
      rev = "8d548bb720feaf31dd026457bff821cb9a030080";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ns6LIxf8s9NWAVtwyQ4Tsk3HIOQhu0IfRPm/WwV5hM4=";
    };
    date = "2026-08-07";
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-y/U8kQ3HeYf/KvCEQisMjgrfRP/ie7vZjqMU/im1lF0=";
    };
  };
  jellyfin-plugin-sso = {
    pname = "jellyfin-plugin-sso";
    version = "4.0.0.6";
    src = fetchTarball {
      url = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v4.0.0.6/sso-authentication_4.0.0.6.zip";
      sha256 = "sha256-U7TA16j8ovPa7zhSDGskb1fuU2Icm4J7EJCCdcUmp+Q=";
    };
  };
  jellyfin-plugin-sso-src = {
    pname = "jellyfin-plugin-sso-src";
    version = "v4.0.0.6";
    src = fetchFromGitHub {
      owner = "Buco7854";
      repo = "jellyfin-plugin-sso";
      rev = "v4.0.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PgDjXTrMCpTKth/nVczBHUCAuaGn8ZWbTXY5yVH5A6M=";
    };
  };
  komari-agent = {
    pname = "komari-agent";
    version = "1.2.60";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari-agent";
      rev = "1.2.60";
      fetchSubmodules = false;
      sha256 = "sha256-SsM/RbwdWmKty+6ueL4J9auKcPkRMNX59Imko3oPOiQ=";
    };
  };
  limes = {
    pname = "limes";
    version = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
    src = fetchgit {
      url = "https://github.com/js0ny/limes.git";
      rev = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nt/y2H5+T9mA0Lvv23dig4BZUUGib16tPiCb0+Fg14Q=";
    };
    date = "2026-07-07";
  };
  mpv-bilibili-sponsorblock = {
    pname = "mpv-bilibili-sponsorblock";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "test482";
      repo = "mpv-bilibili-sponsorblock";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-W3H/mHmXIdmfH8k2wFXfalF4W7WDQIDAW0wo11n3V04=";
    };
  };
  msd_lite = {
    pname = "msd_lite";
    version = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
    src = fetchFromGitHub {
      owner = "rozhuk-im";
      repo = "msd_lite";
      rev = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
      fetchSubmodules = true;
      sha256 = "sha256-+LMcsU/kfaRD/0OTN4IN84GeFOsuiGCKjtvVP4dyY6g=";
    };
    date = "2026-07-20";
  };
  noname = {
    pname = "noname";
    version = "v1.11.5";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.5";
      fetchSubmodules = false;
      sha256 = "sha256-eut+46GB+szbfUN3drtKfXXQiRbCnxGT61WN6z9H98Q=";
    };
  };
  openlogi = {
    pname = "openlogi";
    version = "v0.6.23";
    src = fetchFromGitHub {
      owner = "AprilNEA";
      repo = "OpenLogi";
      rev = "v0.6.23";
      fetchSubmodules = false;
      sha256 = "sha256-tdnHEYOLXGis3u17QYsVWkmDtvkklqLhgLJqGX/coMA=";
    };
  };
  oroot = {
    pname = "oroot";
    version = "99992d13696833ebb31372a2eb5072c3c1b79a33";
    src = fetchgit {
      url = "https://github.com/js0ny/oroot.git";
      rev = "99992d13696833ebb31372a2eb5072c3c1b79a33";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IEfxtTh271WtPKVZhKiz+mEFKS2ACM7aS4Bnk8n2kcc=";
    };
    date = "2026-08-02";
  };
  proton-drive-cli-darwin-arm64 = {
    pname = "proton-drive-cli-darwin-arm64";
    version = "0.7.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.7.0/darwin-arm64/proton-drive";
      sha256 = "sha256-uTHY1ePqcrjcoUM/b+uQ/6ACQw1p+1gZZH5JpbmdyBQ=";
    };
  };
  proton-drive-cli-linux-arm64 = {
    pname = "proton-drive-cli-linux-arm64";
    version = "0.7.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.7.0/linux-arm64/proton-drive";
      sha256 = "sha256-XW7TKTy1gb/pL8ZUStmzLA24MgJtQ4wX3vKPXNQ9ZsI=";
    };
  };
  proton-drive-cli-linux-x64 = {
    pname = "proton-drive-cli-linux-x64";
    version = "0.7.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.7.0/linux-x64/proton-drive";
      sha256 = "sha256-Tjx0p6JdoA16DKnuIjqbewsjjaNXq2/P7gSlwxPd9NE=";
    };
  };
  ratune = {
    pname = "ratune";
    version = "v0.15.2";
    src = fetchFromGitHub {
      owner = "acmagn";
      repo = "ratune";
      rev = "v0.15.2";
      fetchSubmodules = false;
      sha256 = "sha256-LkEzYYEVkOL/f1BDa9sYSXuXlCk1i2PZ+1+sHzB+KBc=";
    };
  };
  rime-cantonese = {
    pname = "rime-cantonese";
    version = "latest";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "rime-cantonese";
      rev = "latest";
      fetchSubmodules = false;
      sha256 = "sha256-M2zFuhKAmSJ3X7zP0+itakhmuHqwtxZVOHS/fn+NSZo=";
    };
  };
  rime-dieghv = {
    pname = "rime-dieghv";
    version = "1709bb786a144de7be2229755011fde9034457de";
    src = fetchgit {
      url = "https://github.com/kahaani/dieghv.git";
      rev = "1709bb786a144de7be2229755011fde9034457de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMViEO0nxNEjVZbHwB0e9vSpe5TfHV7CuJoouS84Pjg=";
    };
    date = "2019-02-11";
  };
  rime-latex = {
    pname = "rime-latex";
    version = "858f2abc645f0e459e468e98122470ce20b16b30";
    src = fetchgit {
      url = "https://github.com/shenlebantongying/rime_latex.git";
      rev = "858f2abc645f0e459e468e98122470ce20b16b30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i8Rgze+tQhbE+nl+JSj09ILXeUvf6MOS9Eqsuqis1n0=";
    };
    date = "2025-04-03";
  };
  rime-lmdg-zh-hans = {
    pname = "rime-lmdg-zh-hans";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-MW285vytIy2GebvKOdWmggyHCz/pVKW5jkg4remyqDE=";
    };
  };
  rime-lmdg-zh-hant = {
    pname = "rime-lmdg-zh-hant";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hant.gram";
      sha256 = "sha256-Yx70ezhPgcGzsI5hjvwp2/B3Ks8KDHgCbjgt8rAHCDA=";
    };
  };
  rime-wanxiang-flypy = {
    pname = "rime-wanxiang-flypy";
    version = "v17.2.4";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v17.2.4/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-7TMQcH0UaemlVJ+mvIKu9Zj7+IKn1D5qX4cyXCcg0CM=";
    };
  };
  rime-wanxiang-zrm = {
    pname = "rime-wanxiang-zrm";
    version = "v17.2.4";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v17.2.4/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-ib8U25sD8szfuUDB+L7i20MJPBcFVW9eoyW4QuKuDs0=";
    };
  };
  sops-nvim = {
    pname = "sops-nvim";
    version = "4de0cb71746d7a6de6311c85bc39873e56bcefc7";
    src = fetchgit {
      url = "https://github.com/trixnz/sops.nvim.git";
      rev = "4de0cb71746d7a6de6311c85bc39873e56bcefc7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pMnAGm7tkgM5pxhNEs06Qdx69qztMd14uNpuRi4I4qE=";
    };
    date = "2026-07-11";
  };
  udpxy = {
    pname = "udpxy";
    version = "1.0-25.2";
    src = fetchFromGitHub {
      owner = "pcherenkov";
      repo = "udpxy";
      rev = "1.0-25.2";
      fetchSubmodules = false;
      sha256 = "sha256-v+w4Y6MyJqUrgwuYUYTZW0Zn1jhW4vEpgBEQyEjvkzg=";
    };
  };
  vireo = {
    pname = "vireo";
    version = "v1.7.0";
    src = fetchFromGitHub {
      owner = "hyprlab";
      repo = "vireo";
      rev = "v1.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-dicvn51CXo7STHArC6yyKXqBmAy79GP9AMb71MUKl+s=";
    };
  };
  waywallen = {
    pname = "waywallen";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-882hr8+krSLI5JPaB3wggcCz6UXDoln0CxbkEDCE8Fs=";
    };
  };
  waywallen-display = {
    pname = "waywallen-display";
    version = "v0.3.1";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen-display";
      rev = "v0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-vKBo7JlaxZc0YkbBA6GPsF/Mpa9vqoQP9O9eRoMRNMU=";
    };
  };
  waywallen-main-page-webp = {
    pname = "waywallen-main-page-webp";
    version = "v0.3.1";
    src = fetchurl {
      url = "https://media.githubusercontent.com/media/waywallen/waywallen/v0.3.1/ui/assets/main_page.webp";
      sha256 = "sha256-US6vRPPip7LjLsjVpet+jW2AyIH/AcUkYoCaI+zoFBs=";
    };
  };
  wdotool = {
    pname = "wdotool";
    version = "v0.5.3";
    src = fetchFromGitHub {
      owner = "cushycush";
      repo = "wdotool";
      rev = "v0.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-kmEMkkU5cy2AqEzbpm4Dp+FzguzldzWqD5KSr7uskLE=";
    };
  };
}
