# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bbdown = {
    pname = "bbdown";
    version = "1.6.3";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-IXSK4XrdDbSbjvx0XsjZqi53mo4tTeFL3p0gegaNCA0=";
    };
  };
  chatgpt = {
    pname = "chatgpt";
    version = "26.810.52044";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/linux/deb/latest/chatgpt_amd64.deb";
      sha256 = "sha256-cIoVobt24rt/DjduUUU5H6J3rTpkBXwdMlN73CobTm4=";
    };
  };
  clair-obscur-fix = {
    pname = "clair-obscur-fix";
    version = "0.0.15";
    src = fetchTarball {
      url = "https://codeberg.org/Lyall/ClairObscurFix/releases/download/0.0.15/ClairObscurFix_0.0.15.zip";
      sha256 = "sha256-lJV+ujiSx/IkjLG5UcA54+3ucNscV2KBwOYnIlUMM2s=";
    };
  };
  coredump-notify = {
    pname = "coredump-notify";
    version = "7932978149036a952220e9263fab1734aea983c2";
    src = fetchgit {
      url = "https://github.com/js0ny/coredump-notify.git";
      rev = "7932978149036a952220e9263fab1734aea983c2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OX4O2Oezm7a7o8bbNk7wASVSUVI2w1xJZki625RRuPo=";
    };
    date = "2026-08-15";
  };
  danmakufactory = {
    pname = "danmakufactory";
    version = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "3813e93b13b087e95901d1822baf9c3540e3f3f6";
      fetchSubmodules = false;
      sha256 = "sha256-wRQjWlG3R4IbcMedL7v36VZE3CcUkbeYwgr1Ex+7NGI=";
    };
    date = "2026-07-27";
  };
  dirstat-rs = {
    pname = "dirstat-rs";
    version = "v0.3.7";
    src = fetchFromGitHub {
      owner = "scullionw";
      repo = "dirstat-rs";
      rev = "v0.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-gDIUYhc+GWbQsn5DihnBJdOJ45zdwm24J2ZD2jEwGyE=";
    };
  };
  dump-tabs = {
    pname = "dump-tabs";
    version = "745e347bcf9a2bec87370a33d4929d07af09f011";
    src = fetchgit {
      url = "https://github.com/js0ny/dump-tabs.yazi.git";
      rev = "745e347bcf9a2bec87370a33d4929d07af09f011";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Etx5LX9TuiGoxLe6eIH6pYM1wXzsqQ/uY6clq/AiusY=";
    };
    date = "2026-07-09";
  };
  dwproton = {
    pname = "dwproton";
    version = "dwproton-11.0-11";
    src = fetchTarball {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-11/dwproton-11.0-11-x86_64.tar.xz";
      sha256 = "sha256-p1x1UAuXLG0MpYcyrssudKwpCRlKAPPxrv7UFyPe2lI=";
    };
  };
  emacs-typst-overlay = {
    pname = "emacs-typst-overlay";
    version = "292cea49c5073a54b02aa5eb12467a4ac9919097";
    src = fetchgit {
      url = "https://github.com/hesampakdaman/typst-overlay.git";
      rev = "292cea49c5073a54b02aa5eb12467a4ac9919097";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ew7t4bVxJ9GqaYFqV8esUqAfs1nKzZbnNkdkOS88nv4=";
    };
    date = "2026-06-04";
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "65d4b5d6ec3ca3570c81460905465cbc78e736f6";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks.git";
      rev = "65d4b5d6ec3ca3570c81460905465cbc78e736f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Dsxb3ijrFQQ+Ce0O631Hh7XjsNMpcVt+2Umt+LaDCVc=";
    };
    date = "2026-08-15";
  };
  flyline = {
    pname = "flyline";
    version = "v1.6.2";
    src = fetchFromGitHub {
      owner = "HalFrgrd";
      repo = "flyline";
      rev = "v1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-UAHb54S4WUu5IyYiqVvDQYTShaIaBBL78POqCEonEqc=";
    };
  };
  forgejo-file-icons = {
    pname = "forgejo-file-icons";
    version = "6143bd16c1b2a30e97d78e4ffb3b09a2840d1e20";
    src = fetchgit {
      url = "https://github.com/js0ny/forgejo-file-icons.git";
      rev = "6143bd16c1b2a30e97d78e4ffb3b09a2840d1e20";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XrHIZQcVe5QmmoihaTIHijG4BV12plNHSj+Lc0IOO20=";
    };
    date = "2026-08-10";
  };
  go-fast-note-sync = {
    pname = "go-fast-note-sync";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "erichll";
      repo = "go-fast-note-sync";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-y/U8kQ3HeYf/KvCEQisMjgrfRP/ie7vZjqMU/im1lF0=";
    };
  };
  jellyfin-plugin-sso = {
    pname = "jellyfin-plugin-sso";
    version = "4.0.0.6";
    src = fetchTarball {
      url = "https://github.com/Buco7854/jellyfin-plugin-sso/releases/download/v4.0.0.6/sso-authentication_4.0.0.6.zip";
      sha256 = "sha256-U7TA16j8ovPa7zhSDGskb1fuU2Icm4J7EJCCdcUmp+Q=";
    };
  };
  jellyfin-plugin-sso-src = {
    pname = "jellyfin-plugin-sso-src";
    version = "v4.0.0.6";
    src = fetchFromGitHub {
      owner = "Buco7854";
      repo = "jellyfin-plugin-sso";
      rev = "v4.0.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-PgDjXTrMCpTKth/nVczBHUCAuaGn8ZWbTXY5yVH5A6M=";
    };
  };
  komari-agent = {
    pname = "komari-agent";
    version = "1.2.60";
    src = fetchFromGitHub {
      owner = "komari-monitor";
      repo = "komari-agent";
      rev = "1.2.60";
      fetchSubmodules = false;
      sha256 = "sha256-SsM/RbwdWmKty+6ueL4J9auKcPkRMNX59Imko3oPOiQ=";
    };
  };
  limes = {
    pname = "limes";
    version = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
    src = fetchgit {
      url = "https://github.com/js0ny/limes.git";
      rev = "0cd6451c4558919ffeceec51f11b7fa8b912318e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Nt/y2H5+T9mA0Lvv23dig4BZUUGib16tPiCb0+Fg14Q=";
    };
    date = "2026-07-07";
  };
  mpv-bilibili-sponsorblock = {
    pname = "mpv-bilibili-sponsorblock";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "test482";
      repo = "mpv-bilibili-sponsorblock";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-W3H/mHmXIdmfH8k2wFXfalF4W7WDQIDAW0wo11n3V04=";
    };
  };
  msd_lite = {
    pname = "msd_lite";
    version = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
    src = fetchFromGitHub {
      owner = "rozhuk-im";
      repo = "msd_lite";
      rev = "fa68e131343fb58c67ad77b2d26f2cb7c49a2c95";
      fetchSubmodules = true;
      sha256 = "sha256-+LMcsU/kfaRD/0OTN4IN84GeFOsuiGCKjtvVP4dyY6g=";
    };
    date = "2026-07-20";
  };
  noname = {
    pname = "noname";
    version = "v1.11.5.1";
    src = fetchFromGitHub {
      owner = "libnoname";
      repo = "noname";
      rev = "v1.11.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-Kc//eccLUl1wkj+3GJYSadxPblLWKjxBWLFUO863mTI=";
    };
  };
  openlogi = {
    pname = "openlogi";
    version = "v0.7.1";
    src = fetchFromGitHub {
      owner = "AprilNEA";
      repo = "OpenLogi";
      rev = "v0.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-+LHtffr/m4abosbqh1KCkD5iy/GANLVIMac+lmjJWxc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-+LHtffr_m4abosbqh1KCkD5iy_GANLVIMac+lmjJWxc=/Cargo.lock";
      outputHashes = {
        "proptest-1.10.0" = "sha256-p5NTcHhruI8QQvANACg8AMRVNmuvGxs2NLit+/8PaWo=";
        "zed-font-kit-0.14.1-zed" = "sha256-KXygi0olNQi5yM8eaJVykNDtbPMDjT+cWPBF8UrtXR4=";
        "zed-reqwest-0.12.15-zed" = "sha256-p4SiUrOrbTlk/3bBrzN/mq/t+1Gzy2ot4nso6w6S+F8=";
        "collections-0.1.0" = "sha256-Av+unZNI39dEb+zwSIU+SkEjqagHWrc7W8KehEgQ4H8=";
        "zed-scap-0.0.8-zed" = "sha256-BihiQHlal/eRsktyf0GI3aSWsUCW7WcICMsC2Xvb7kw=";
        "gpui-component-0.5.2" = "sha256-yOXdgxQgfvGN2/+OdDnl1pYti0DoGFvS3Tyqvj3Bkng=";
        "gpui-updater-0.0.7" = "sha256-hxdATcCif7csqKLNoi41ETe09Ym6zM4rVzYvBDEvVg4=";
        "xim-ctext-0.3.0" = "sha256-pRT4Sz1JU9ros47/7pmIW9kosWOGMOItcnNd+VrvnpE=";
      };
    };
  };
  oroot = {
    pname = "oroot";
    version = "99992d13696833ebb31372a2eb5072c3c1b79a33";
    src = fetchgit {
      url = "https://github.com/js0ny/oroot.git";
      rev = "99992d13696833ebb31372a2eb5072c3c1b79a33";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IEfxtTh271WtPKVZhKiz+mEFKS2ACM7aS4Bnk8n2kcc=";
    };
    date = "2026-08-02";
  };
  proton-drive-cli-darwin-arm64 = {
    pname = "proton-drive-cli-darwin-arm64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/darwin-arm64/proton-drive";
      sha256 = "sha256-3I/BTenvB/zvKP4gQFG7ZynEnPV5FwyM4a1mmiZ2lxE=";
    };
  };
  proton-drive-cli-linux-arm64 = {
    pname = "proton-drive-cli-linux-arm64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/linux-arm64/proton-drive";
      sha256 = "sha256-CGvEdApzy460kA1Rg2v/DDMt2jkLPweA2fgF/VwqX+M=";
    };
  };
  proton-drive-cli-linux-x64 = {
    pname = "proton-drive-cli-linux-x64";
    version = "0.8.0";
    src = fetchurl {
      url = "https://proton.me/download/drive/cli/0.8.0/linux-x64/proton-drive";
      sha256 = "sha256-lEPXcXGciSeQ2xfm8C7Nma18U1kzKfOmfHdnfc5XdzU=";
    };
  };
  ratune = {
    pname = "ratune";
    version = "v0.15.2";
    src = fetchFromGitHub {
      owner = "acmagn";
      repo = "ratune";
      rev = "v0.15.2";
      fetchSubmodules = false;
      sha256 = "sha256-LkEzYYEVkOL/f1BDa9sYSXuXlCk1i2PZ+1+sHzB+KBc=";
    };
  };
  rime-cantonese = {
    pname = "rime-cantonese";
    version = "259f0e48bba840c3a2e0d117539e96937f3d89bc";
    src = fetchgit {
      url = "https://github.com/rime/rime-cantonese.git";
      rev = "259f0e48bba840c3a2e0d117539e96937f3d89bc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ctyYZQVCd9Sc7oqPmP4lO1Q0TYDQILqt/BRloaEWjPg=";
    };
    date = "2026-08-13";
  };
  rime-dieghv = {
    pname = "rime-dieghv";
    version = "1709bb786a144de7be2229755011fde9034457de";
    src = fetchgit {
      url = "https://github.com/kahaani/dieghv.git";
      rev = "1709bb786a144de7be2229755011fde9034457de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rMViEO0nxNEjVZbHwB0e9vSpe5TfHV7CuJoouS84Pjg=";
    };
    date = "2019-02-11";
  };
  rime-hokkien = {
    pname = "rime-hokkien";
    version = "e52e8bf337f161097cd3798c0173ba4e39b44396";
    src = fetchgit {
      url = "https://github.com/hokkien-writing/rime-hokkien.git";
      rev = "e52e8bf337f161097cd3798c0173ba4e39b44396";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-60NlGg2vLkOmth/O3o4G/n/XzJ9cB/tfPtCYRGbOnCs=";
    };
    date = "2026-05-04";
  };
  rime-latex = {
    pname = "rime-latex";
    version = "858f2abc645f0e459e468e98122470ce20b16b30";
    src = fetchgit {
      url = "https://github.com/shenlebantongying/rime_latex.git";
      rev = "858f2abc645f0e459e468e98122470ce20b16b30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i8Rgze+tQhbE+nl+JSj09ILXeUvf6MOS9Eqsuqis1n0=";
    };
    date = "2025-04-03";
  };
  rime-lmdg-zh-hans = {
    pname = "rime-lmdg-zh-hans";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram";
      sha256 = "sha256-a81qxhNpt0AYI/fc5ZomWYFA6sW5Q884Zun0EgS2rfs=";
    };
  };
  rime-lmdg-zh-hant = {
    pname = "rime-lmdg-zh-hant";
    version = "LTS";
    src = fetchurl {
      url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hant.gram";
      sha256 = "sha256-Yx70ezhPgcGzsI5hjvwp2/B3Ks8KDHgCbjgt8rAHCDA=";
    };
  };
  rime-teochew = {
    pname = "rime-teochew";
    version = "7c80a292fee4001e28ca4f539c23924ab3fc3924";
    src = fetchgit {
      url = "https://github.com/OpenTeochew/rime-teochew.git";
      rev = "7c80a292fee4001e28ca4f539c23924ab3fc3924";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TfCY0Y1CPVJP0mV0cnAPh3y3g39z2yYQvycT97jWBuE=";
    };
    date = "2026-07-05";
  };
  rime-wanxiang-flypy = {
    pname = "rime-wanxiang-flypy";
    version = "v17.3.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v17.3.0/rime-wanxiang-flypy-fuzhu.zip";
      sha256 = "sha256-ndK8aX9MqI30FRw9ZgcJcqT/By9e8q/rTVcH9axVxS4=";
    };
  };
  rime-wanxiang-zrm = {
    pname = "rime-wanxiang-zrm";
    version = "v17.3.0";
    src = fetchurl {
      url = "https://github.com/amzxyz/rime_wanxiang/releases/download/v17.3.0/rime-wanxiang-zrm-fuzhu.zip";
      sha256 = "sha256-lowg5ECM2a7sJmB+zDzyUg1AAIhIphTIBXJ3u4A78/I=";
    };
  };
  sops-nvim = {
    pname = "sops-nvim";
    version = "4de0cb71746d7a6de6311c85bc39873e56bcefc7";
    src = fetchgit {
      url = "https://github.com/trixnz/sops.nvim.git";
      rev = "4de0cb71746d7a6de6311c85bc39873e56bcefc7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pMnAGm7tkgM5pxhNEs06Qdx69qztMd14uNpuRi4I4qE=";
    };
    date = "2026-07-11";
  };
  udpxy = {
    pname = "udpxy";
    version = "1.0-25.2";
    src = fetchFromGitHub {
      owner = "pcherenkov";
      repo = "udpxy";
      rev = "1.0-25.2";
      fetchSubmodules = false;
      sha256 = "sha256-v+w4Y6MyJqUrgwuYUYTZW0Zn1jhW4vEpgBEQyEjvkzg=";
    };
  };
  vireo = {
    pname = "vireo";
    version = "v1.8.1";
    src = fetchFromGitHub {
      owner = "hyprlab";
      repo = "vireo";
      rev = "v1.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-85yTavASNJOkxkXHZqf6AaQmM2TVwZFqTYJ55UnM/QA=";
    };
  };
  waywallen = {
    pname = "waywallen";
    version = "v0.3.4";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen";
      rev = "v0.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-xjkRdgwTcHzfqOyWKt2Lq0uqFI+ox3fVv5ReM2AvDLI=";
    };
  };
  waywallen-display = {
    pname = "waywallen-display";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "waywallen";
      repo = "waywallen-display";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-3CMPCulvUwG5m8d894cHAwPKLxhmOEj8t498ujlOPZw=";
    };
  };
  waywallen-main-page-webp = {
    pname = "waywallen-main-page-webp";
    version = "v0.3.4";
    src = fetchurl {
      url = "https://media.githubusercontent.com/media/waywallen/waywallen/v0.3.4/ui/assets/main_page.webp";
      sha256 = "sha256-4+RMgz8Jz3PZFWKYtSdGUBKNjq53zh/Yce+702band0=";
    };
  };
  wdotool = {
    pname = "wdotool";
    version = "v0.5.3";
    src = fetchFromGitHub {
      owner = "cushycush";
      repo = "wdotool";
      rev = "v0.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-kmEMkkU5cy2AqEzbpm4Dp+FzguzldzWqD5KSr7uskLE=";
    };
  };
}
